language: java
jdk: oraclejdk8
git:
  depth: false
branches:
  only:
  - master
  - "/^[0-9]{1,4}\\.[0-9]{1,4}\\.[0-9]{1,4}(-[rR][cC][0-9]{1,4})?$/"
script: "./gradlew build"
env:
  global:
  - secure: CZVUhcViotT5HQN65u/2sih/mF9Oc9PQxKhVFyzWjxvdSeCbAXl2bNUcD90m8nj0bk4Is1Cg6TtkRsmHVmEaofq2ACtNqRMY598V8UrIpgoCPKl+/OgEXxT1P/2FZ1YQWtAsdBJ7MUcpgeQ8Us/XztdbJkw2q30kJiJg+rbIy20dTVswdctg9fpaysvjxeLed4vtrpxniV09EOffopoYhYRfiF0x4ggNoDvTcvWT3W0azxsuWksfgOBcd24g32pdjmKOSRiLwpkG0LSEBJL74lemDe6kr41w2g4JTsA8p0+6PHsZzpIGpnH2o+8imeTlOHKUGfJ3K45b5XpVvIQX1LEurvDNg7Zp+tAXT4+nYq/JprBb2UmWh5GIby/yLhmfRgfM5bJiBrxUP1A7xWHbXaYVHXPELZX7Ih7+ZutaJiFkN+ZewHsU5slWR/bDv4q7yXrovfLxaTWoJiImYxGc1cZXWg6v8VWNf30CfwZDeGzHPoV1SYDpwr0WETp9FrpaZ0CPCMS2mqI7c9xY3+xNA2fEzprhpjXWKo/Myq80eTvobxl0v4Tt1gLG4ODq+4U+vaO1erPX5mvs7Eq+Psh8V2ljb2qsoYdmh6XcnovZ9izg/ZFuyHVFsTFlKDSd1GNSuiIshGwn28RSstY2tjAr9Ile4GQkQyLYz+ygumH8QSM=
  - secure: Wj6qGOfF+3VExJ4Q/A6+fLvjU6YHguPJVITaiCiIiUgwk65kDQQgJFCQqoKn3ND174I1lful90j2QnQ7VaiTFdC2EWzgMu0wh2pCdYtiZG1tkvKe5M9eqWA3mh1ERNbyMZLg5g1XH/UsKwNj1m91xU7hkuXW1KS/lVgclo2UgCX2sqPJjYiAFrXQ+m6mC1/ZD5FzdbX8axF1xWVDFOeETUZeXbWduanMtmoT8T08mX9mB8hlf6ls6ILAxwC5oXVzicgPiIsnbMWi3tLL1XaUtsr9/AXFJDnJj51N0GnGu/RWtZdJMTKzN+bVsb84i2jJDNP4+8Fj/k7v1EsuMo3nhg1U+Wo9wDCcczaXZd+Y1tf+eyfgj5soewZpCZ7oyeGiHqh4XUL4duJtGb4twvz8meQJ42b/6f4zINJEnaWJNZU/JDCgVTyNrqqbHeMfQ20RjFCYzBSh49bXX6bP3piasWzvYg50QFb0OqyM0i1YOkN3vtPmK9EWl962XOitzXh3TtksoELZGLkkwFi6tiIqf/+cqCuAk8BvIMzQZyKL8JZA/9KVqxM+dr9YOzJViTTZP+Ev5gjp+WDeW5bJgPyqpUwjjCbM9C5OATCKlzwM8MVXXYwVKQyUwdCdkUKSFUBz6tYkvsRoA5WWBjJW8eBPYSKmbDL3tMp8qx4y2Lrg+xA=
deploy:
- provider: releases
  api_key:
    secure: Yw/h1aX1tbCr8xEiAN1OwDmbREwE3hawQ3nzTzNKe2nTZGq6jkXPwX7Lsm5uQh27bDBAu9VypbRcZbF7IXFwy5pTbIY9289bbOpDESFJvGtC54Ac/fv4ynKqsjkmL6DhfvjAsboC8prBKkDTdcRLMApJLOazZjrR2w8+T0cwtasT4cnRRwqdT47nPHyr9LOEEZYzcI6h4bWuqGzGLzTwrPRHsuIHmRxcU2aQ+16jA7a8CJUbingLRNlz/a1r6I90o7+NhSSr8hsHHHN6PjP+U9/nmmkX8C90sshXkwxo4VnCRu01Ty7ukTDeC8ZINVA/DYq3s2vaetL0ambJvBZ+hZPVy5b0pGf/AftpA85DLHNAzG7oSyftpHJ6Lfoh4y2yxnXhcJ+kYOZb4ti+Ri89ribEzXwMS2n0VThdofkCGDxYGIpgIUjDbnBFZA2MCoq9qLq/fFCUkL5uf3mBc0OhWF9Zi9bZKDGm+Z5wYFQCrfGmA47bGND76AHmcUCFbW6Obq0pOor+NBlv2wgWO6scnH+1UlCvpDFfGxYdQmKsJzJGNOpokWpqGA3vHwp0mhjaeFh1Z1r0u14AOk9fqgcYy7YwaTignlEqihsm8VYIkGrMC9NxTWvdydTYFbM39m75ureq3UDrtxYkB+/xBABcZ9TqvD+NX6a4Blgoi8IBXQ4=
  skip_cleanup: true
  file_glob: true
  file: git-version/build/libs/git-version-*.jar
  on:
    tags: true
    repo: moonlitdoor/mld-git-version
- provider: script
  script: "./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET"
  on:
    tags: true
notifications:
  slack:
    rooms:
      - secure: TpQ8x1Iv6JABZ0ZoHRgBy0fMcjG7hazfUwgA/6TqEurSaBRTM6GfgekGwiEXkVctwgVrQk+r4AFLUYQFXMm5JLSO1+kIlkKcKDYlQHZbUmxOqPMnKS7bd1rHUBdg9ZDehZ/WNqUE+w29ng7OgVFg9E3k8/CVaokq0Gj9addpsnvQx47inkYvjl6rV1uBbE9eTnytA9LpvWZVDZgiOEr5TNt16AmFxtV5bbZzlxS/MlUtcbTWWZ5srsVCQ4VYf8BtbtP9jcm+Y+Uud92eaWXn+GxgQ3UQveu7+ylI8s6BO5+Qh9jtStw8hSpb6cA9OGyiGTh5H0kD00HlQNfMSgjM6OcXB7IlbwV5amqCi30jJHeoSnwN9Tom0z/xo2B1VntBBKdRn+oTiIn8J1WyZ+CuVK2cDRg0tsdnkS1Zv0o01XxKRLnYixMK6tUGa9M/6zJ6KAfDrPKg6DocXZIExXzaRdOWbbuiv5WyevVHZULfvYFytnW9B23vu+iPnMX+qNdvSCBS1zyC8aiqiGBUOjXk3cx16uv8srJ3f0+peDPmCFzn9n6x8rw2IobT/8nI87cz/iTjNB7zQ68Yo45/shgdQKi4ukCw7f1wMm8b0Q1yA2ZaPmktXCYXY6+QBJTXHkNVXCeHogcUF8DT3dq0xMWBJ7J4EtAm7EnmdJRGOZWo/h4=
