language: java

jdk: oraclejdk8

git:
  depth: false

branches:
  only:
  - master
  - "/^[0-9]{1,4}\\.[0-9]{1,4}\\.[0-9]{1,4}(-[rR][cC][0-9]{1,4})?$/"

script: "./gradlew build"

env:
  - secure: "hTSP/4TrRMvPUjxMtioE34q1xXRAiimQYcz9SIPrhHNwDXGb5bvBOsQ5zHF8+Bn6rowHqKhBSuGmOfV9AT4qcDKQoUjbGGp7QwkG7ygLKITSisEp4Biuinw7kMNmHSh9iMlwdETchnpsh6wwr5LVVvwbFbTy3a2sR/RLBWg97z5HplO5Wu+kkqaTRdNxOwmFAroDKGvqYCqFeedtLmltYj6XtZqUpD2zETCx6KDKZNNVt/xFU8VVVUBloLPm6t+2IiP8WVxrvJ5ZD/pyIx3pNHx6J/DE21KUorrJ2bY1tSyvacXEo0ZH1gXerue9gtA/C9zook2Q+tzB6TuhFH7PMo7M6zCQaaDadlsLb9c9UXjQVKm8hJp7I1jg1INiCjCHFR5m/TyZxW89H5qcpgKdy7ldiebBzWGlI0MCqdv5s9aipGJzqV8hIK6cnnXdRXS1qgyCeZIbcY+5gxsCrmWsnWELyqnMqYVXEV4Pq8K/U5ETouCTe1egbN8BFzgzeI1R48vEDTtYSIhNVq3HcuV3gMiwHtoKTLBulTj1k3KiwBBoTRFKAF8MIsTOaLbzzvH9+ZoWnlqbMqYGDvQH1keXqA2+664pUIvKqBxSG7A+ik8pcrN4MN3DGDDrvGEMlrx4+K1x6P6JqX8lBcY7NwT8B/CpY+pcM+REooC4IzrStQs="
  - secure: "WylcEJGDweH8rrKOfYXHgEZ1LMXdY4BHjBn0Lo34NyEVVXY6305j0btX3m1oYTAB4i7ZIGRY3LaSMjzAuc7FwWwqt2UZTyvKJlLNB2oIZmOuHtqq9CTb0etkbHdBjr4bw7RZetmHjZggmhOms5sqh7Ih6xf5Dak4HFDXz0Uk63QRqH9WzkgK6uJ22XKYPvTIR5HfWJMgCRFTaz34co4DSDfppR9OyXgRup+I9tVMflCSCnfMyP0s3eCNGx7HTOptdVqtjCW3WMuXavOaSt6rgkL+EVu2qZUdMtIoZsf7MyWfT3C2HbpsM2QgiGpmuExy5j3nN70RsIJCHLX1fhV6ErwplqNDOSyQRK+fKgK4vK2FnxttMD++eBz5EGxFz/mvZ7BrU3bOt99SUDmuji0KxNXkxjF2WBMahfuah9m5tKaGZlycFbSTDp6sHQ1m2QBGoS14G/2G7CwusZ55xwFLfQHkaKWYmkRYhEoOD5zORDDyzUBMfx7Ne5wBL3ZiKry34fyN4rOlsuduPVENph+HipG5b0clKebE7CvUplct/vd9093FjhJkx2lvAtvjFeVJ0moBD+Tk8su29+l/qvCNgPg3cPumf6zZXfkc5Rtbg5Ehm/Gokg3mPHFBFP6G1gzUQBqtoRS0Y/qL9IFU7Cztp1pYLcqh9C7F7JF6H9L39zA="

deploy:
  provider: releases
  api_key:
    secure: Yw/h1aX1tbCr8xEiAN1OwDmbREwE3hawQ3nzTzNKe2nTZGq6jkXPwX7Lsm5uQh27bDBAu9VypbRcZbF7IXFwy5pTbIY9289bbOpDESFJvGtC54Ac/fv4ynKqsjkmL6DhfvjAsboC8prBKkDTdcRLMApJLOazZjrR2w8+T0cwtasT4cnRRwqdT47nPHyr9LOEEZYzcI6h4bWuqGzGLzTwrPRHsuIHmRxcU2aQ+16jA7a8CJUbingLRNlz/a1r6I90o7+NhSSr8hsHHHN6PjP+U9/nmmkX8C90sshXkwxo4VnCRu01Ty7ukTDeC8ZINVA/DYq3s2vaetL0ambJvBZ+hZPVy5b0pGf/AftpA85DLHNAzG7oSyftpHJ6Lfoh4y2yxnXhcJ+kYOZb4ti+Ri89ribEzXwMS2n0VThdofkCGDxYGIpgIUjDbnBFZA2MCoq9qLq/fFCUkL5uf3mBc0OhWF9Zi9bZKDGm+Z5wYFQCrfGmA47bGND76AHmcUCFbW6Obq0pOor+NBlv2wgWO6scnH+1UlCvpDFfGxYdQmKsJzJGNOpokWpqGA3vHwp0mhjaeFh1Z1r0u14AOk9fqgcYy7YwaTignlEqihsm8VYIkGrMC9NxTWvdydTYFbM39m75ureq3UDrtxYkB+/xBABcZ9TqvD+NX6a4Blgoi8IBXQ4=
  skip_cleanup: true
  file_glob: true
  file: git-version/build/libs/git-version-*.jar
  on:
    tags: true
    repo: moonlitdoor/mld-git-version
  provider: script
  script: "./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET"
  on:
    tags: true
