language: java

jdk: oraclejdk8

git:
  depth: false

branches:
  only:
  - master
  - "/^[0-9]{1,4}\\.[0-9]{1,4}\\.[0-9]{1,4}(-[rR][cC][0-9]{1,4})?$/"

script: "./gradlew build"

deploy:
  provider: releases
  api_key:
    secure: Yw/h1aX1tbCr8xEiAN1OwDmbREwE3hawQ3nzTzNKe2nTZGq6jkXPwX7Lsm5uQh27bDBAu9VypbRcZbF7IXFwy5pTbIY9289bbOpDESFJvGtC54Ac/fv4ynKqsjkmL6DhfvjAsboC8prBKkDTdcRLMApJLOazZjrR2w8+T0cwtasT4cnRRwqdT47nPHyr9LOEEZYzcI6h4bWuqGzGLzTwrPRHsuIHmRxcU2aQ+16jA7a8CJUbingLRNlz/a1r6I90o7+NhSSr8hsHHHN6PjP+U9/nmmkX8C90sshXkwxo4VnCRu01Ty7ukTDeC8ZINVA/DYq3s2vaetL0ambJvBZ+hZPVy5b0pGf/AftpA85DLHNAzG7oSyftpHJ6Lfoh4y2yxnXhcJ+kYOZb4ti+Ri89ribEzXwMS2n0VThdofkCGDxYGIpgIUjDbnBFZA2MCoq9qLq/fFCUkL5uf3mBc0OhWF9Zi9bZKDGm+Z5wYFQCrfGmA47bGND76AHmcUCFbW6Obq0pOor+NBlv2wgWO6scnH+1UlCvpDFfGxYdQmKsJzJGNOpokWpqGA3vHwp0mhjaeFh1Z1r0u14AOk9fqgcYy7YwaTignlEqihsm8VYIkGrMC9NxTWvdydTYFbM39m75ureq3UDrtxYkB+/xBABcZ9TqvD+NX6a4Blgoi8IBXQ4=
  skip_cleanup: true
  file_glob: true
  file: git-version/build/libs/git-version-*.jar
  on:
    tags: true
    repo: moonlitdoor/mld-git-version
